### PR TITLE
#7 renamed maven coordinates and java packages

### PR DESCRIPTION
**Pull request by sylvainlaurent**

### CODE REVIEW

**Comment by vorburger** [comment]
@sylvainlaurent cool! I'm only noticing this now - let me look it over this afternoon and merge it (and do the same for https://github.com/lastnpe/eclipse-null-eea-augments/issues/1), FYI, if you could raise me with an @vorburger when you want me to look at something, that helps to get my attention.. ;-)

**Comment by vorburger** [comment]
@sylvainlaurent only looking at this now I see that you've moved to com.github.lastnpe.m2e namespace.. it doesn't make a huge difference, but I was going to suggest to instead use the org.lastnpe.m2e package, as we have http://lastnpe.org .. I will also use that in https://github.com/lastnpe/eclipse-null-eea-augments/issues/1, and hope to start publishing to http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.lastnpe%22 soon .. would I be too much of a PITA if I suggested you adjust to that?

**Comment by sylvainlaurent** [comment]
done (forced push on this PR).
@vorburger you can merge if OK for you

**Comment by vorburger** [comment]
@ctron just in case you're looking at extending this as we briefly discussed, FYI please note we just moved things around here..

**Comment by ctron** [comment]
Cool. Not right now. So I will wait a bit ;-)

**Pull request merged**
