### PR TITLE
Fixes breaking changes from m2e 2.0.1

### PR DESCRIPTION
**Pull request by arathai**
Move to Eclipse 2022-09 and m2e 2.0.1 and maven.runtime 3.8.0
Needs Java 17 (as does m2e 2.0.1)
see [m2e-core RELEASE_NOTES](https://github.com/eclipse-m2e/m2e-core/blob/master/RELEASE_NOTES.md#201)

### CODE REVIEW

**Comment by vorburger** [comment]
@arathai thanks for this PR!

Would you be interested in and willing to be invited to becoming an active maintainer of this project? You could review and merge PRs, comment on and close issues, etc.

**Comment by arathai** [comment]
I can't promise anything but how can I say no to that offer? :-)

BTW: Closes #44

**Comment by vorburger** [comment]
> but how can I say no to that offer? :-)

I just sent 📤 you an Invite to Join the Organization!

You will need to have 2FA enabled - do you?

**Comment by agentgt** [comment]
It would be nice to get a release of this soon as the plugin breaks the java builder and the only way to get it to work is to disable the plugin.

**Comment by vorburger** [comment]
@arathai I noticed that you accepted the invite. Go ahead and self merge this!

**Comment by arathai** [comment]
If you insist... :)

But I don't know how you published this to Eclipse Marketplace...

**Pull request merged**
