### PR TITLE
Update POMs to 2.0.0-SNAPSHOT and add update site to README

### PR DESCRIPTION
**Pull request by wborn**
Also switches some URLs to HTTPS and removes the Travis CI badge.

See: https://github.com/lastnpe/eclipse-external-annotations-m2e-plugin/issues/47#issuecomment-1345391352

### CODE REVIEW

**Review by kaikreuzer — APPROVED** [review]
Thanks, what a nice clean-up! Now we only need to replace the content on the update site.

**Comment by wborn** [comment]
Can you update the p2 site so the version is updated @kaikreuzer? :slightly_smiling_face:

**Comment by kaikreuzer** [comment]
We had actually missed https://github.com/lastnpe/eclipse-external-annotations-m2e-plugin/pull/50 when merging this PR, it didn't compile. 😉 

I have now built the 2.0.0 version and replaced it on the update site at https://www.lastnpe.org/eclipse-external-annotations-m2e-plugin-p2-site/m2e_2/.

**Comment by wborn** [comment]
Great! 👍 Maybe I find some time to add a GHA PR CI build to prevent this!

**Pull request merged**
