### PR TITLE
Issue #6: Deploy built p2 site to GitHub pages hosted site

### PR DESCRIPTION
**Pull request by vorburger**
https://github.com/lastnpe/eclipse-external-annotations-m2e-plugin-p2-site

see https://github.com/lastnpe/eclipse-external-annotations-m2e-plugin/issues/6

### CODE REVIEW

**Comment by vorburger** [comment]
@victornoel  @kwin  @ctron FYI

**Comment by kaikreuzer** [comment]
What is the url for this p2 repo in the end? Might it be worth to think about a simpler project name than "eclipse-external-annotations-m2e-plugin-p2-site" to make the url better readable?

**Comment by kaikreuzer** [comment]
Ah, found it myself: http://www.lastnpe.org/eclipse-external-annotations-m2e-plugin-p2-site/

How about http://www.lastnpe.org/p2-repo instead? If there are other plugins one day (in different projects under the lastnpe org), all of them could be made available in this repo.

**Comment by vorburger** [comment]
>  If there are other plugins one day (in different projects under the lastnpe org), all of them could be made available in this repo.

Unfortunately NOT actually, due to the way Travis' `deploy: provider: pages` integration works - it `rm -rf` WIPES any current content and then does `git push --force` - which is FINE and CORRECT for what one would typically want e.g. when using this integration to publish a Git Hub pages updates (the use case for which that mechanism seems to originally have been built for).

That is also why when I figured that I removed a master/ branch directory I first wanted inside the repo - that wouldn't have worked anyway in the future, either. It does however work great for the current simple requirement, which is what I wanted to solve here for now.

Based on this, do you still think it should be renamed, and if so to what now?

**Comment by kwin** [comment]
Is this P2 repo supposed to contain releases or SNAPSHOTs. How do you provide older release versions in parallel? From a consumer's point of view two different p2 repo URLs would be preferable. One composite repo for all releases (even older ones) and one containing the latest SNAPSHOT.

**Comment by vorburger** [comment]
@kwin the eclipse-external-annotations-m2e-plugin-p2-site repo is supposed to (and with the current implementation can only ever) contain the latest bleeding edge "SNAPSHOT" like build of this plugin, deployed automatically after each merge into the master branch (it's not really technically a "SNAPSHOT" of course actually, as it's p2 and not Maven).

I've personally currently no requirement (nor the time) to work further on infrastructure to provide older release versions in parallel, but your contributions to extend further upon this basic first "better than the current no p2 repo at all" would be most welcome!

PS: I've just spent a few minutes to see if perhaps this could be made to deploy into like a `master/` sub-folder, to leave the door open for the future, but due to https://github.com/travis-ci/travis-ci/issues/8462 it's not.

**Pull request merged**
